# Generated by scripts/brew-formula.mjs. Do not edit by hand.
class Supercov < Formula
  desc "Code quality and coverage for coding agents"
  homepage "https://supercov.com"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/supercorp-ai/supercov/releases/download/v1.1.0/supercov-cli-darwin-arm64-1.1.0.tgz"
      sha256 "ea09b5ee22df05ae9d79fdcb83b30f5288b23a9b8765ccbfa905b17ee9b17ce5"
    end

    on_intel do
      url "https://github.com/supercorp-ai/supercov/releases/download/v1.1.0/supercov-cli-darwin-x64-1.1.0.tgz"
      sha256 "4652da2cc21a686874186f3ca8552fa758e82e9f4c6d47eb5e4365536bdcc5f1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/supercorp-ai/supercov/releases/download/v1.1.0/supercov-cli-linux-arm64-gnu-1.1.0.tgz"
      sha256 "bb2db52c34f309be4c158dbb283034eb02ab0b844683e76537247f613e9c5f9f"
    end

    on_intel do
      url "https://github.com/supercorp-ai/supercov/releases/download/v1.1.0/supercov-cli-linux-x64-gnu-1.1.0.tgz"
      sha256 "53a1e6f7d08c9e018de59d9a6d9967178799cb491632eed64cc8da2f812eeaa0"
    end
  end

  def install
    # Every channel ships the same npm package, whose files sit under
    # package/. Homebrew strips a single top-level directory when it extracts,
    # so the path here is what is left after that -- unlike cargo-binstall,
    # which does not strip and asks for package/bin.
    bin.install "bin/supercov"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/supercov --version")
  end
end
