# Generated by scripts/brew-formula.mjs. Do not edit by hand.
class Supercov < Formula
  desc "Code quality and coverage for coding agents"
  homepage "https://supercov.com"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/supercorp-ai/supercov/releases/download/v1.2.0/supercov-cli-darwin-arm64-1.2.0.tgz"
      sha256 "3b70a3642a07608af950675ebaf9b94c53f2cc8af71f021f6362cb94abfd30cf"
    end

    on_intel do
      url "https://github.com/supercorp-ai/supercov/releases/download/v1.2.0/supercov-cli-darwin-x64-1.2.0.tgz"
      sha256 "df8f169f291c5f32905fd880c86646274cf84cd15ab32e92e25d991796b6a0b8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/supercorp-ai/supercov/releases/download/v1.2.0/supercov-cli-linux-arm64-gnu-1.2.0.tgz"
      sha256 "794d8f05b482d8b29080124ac8f14e8505d16973306f3d741ab0efa732859c05"
    end

    on_intel do
      url "https://github.com/supercorp-ai/supercov/releases/download/v1.2.0/supercov-cli-linux-x64-gnu-1.2.0.tgz"
      sha256 "89310ccdec078eb93ee0b32669ca9e84eae3a82bdb22f82a2699f95b2a950848"
    end
  end

  def install
    # Every channel ships the same npm package, whose files sit under
    # package/. Homebrew strips a single top-level directory when it extracts,
    # so the path here is what is left after that -- unlike cargo-binstall,
    # which does not strip and asks for package/bin.
    bin.install "bin/supercov"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/supercov --version")
  end
end
