# Generated by scripts/brew-formula.mjs. Do not edit by hand.
class Supercov < Formula
  desc "Coverage for coding agents and software factories"
  homepage "https://supercov.com"
  version "0.0.53"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/supercorp-ai/supercov/releases/download/v0.0.53/supercov-cli-darwin-arm64-0.0.53.tgz"
      sha256 "e66ede845d35bc592ca687d9615254ea7650a95419579106dddd071c3d3de796"
    end

    on_intel do
      url "https://github.com/supercorp-ai/supercov/releases/download/v0.0.53/supercov-cli-darwin-x64-0.0.53.tgz"
      sha256 "e92116d259e50dcef1da9fba2967c3df0ae0d7daa68bd0c1d9ea7b2a6ecab0fe"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/supercorp-ai/supercov/releases/download/v0.0.53/supercov-cli-linux-arm64-gnu-0.0.53.tgz"
      sha256 "6e89c38bea60fdc82218bb214b6db6542b30c437d0f24dd63701058929713097"
    end

    on_intel do
      url "https://github.com/supercorp-ai/supercov/releases/download/v0.0.53/supercov-cli-linux-x64-gnu-0.0.53.tgz"
      sha256 "74100bae485b1eecbeb29c488a5ab6de393657b6e7389e7a05ca5818b360ed26"
    end
  end

  def install
    # Every channel ships the same npm package, whose files sit under
    # package/. Homebrew strips a single top-level directory when it extracts,
    # so the path here is what is left after that -- unlike cargo-binstall,
    # which does not strip and asks for package/bin.
    bin.install "bin/supercov"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/supercov --version")
  end
end
